name: business_card_scanner
description: "Business card scanner mobile app made with Flutter."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  core:
    path: packages/core
  settings:
    path: packages/settings
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.0.10+1
  
  # Camera and Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  image: ^4.1.3
  image_cropper: ^5.0.1
  
  # OCR and ML
  google_mlkit_text_recognition: ^0.11.0
  
  # Storage and Database
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Contact Management
  contacts_service: ^0.6.3
  permission_handler: ^11.0.1
  
  # UI and Utilities
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
